/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package team.dsys.dssearch.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2022-12-04")
public class Transaction implements org.apache.thrift.TBase<Transaction, Transaction._Fields>, java.io.Serializable, Cloneable, Comparable<Transaction> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Transaction");

    private static final org.apache.thrift.protocol.TField TRANS_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("transId", org.apache.thrift.protocol.TType.I32, (short)1);
    private static final org.apache.thrift.protocol.TField KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("key", org.apache.thrift.protocol.TType.I32, (short)2);
    private static final org.apache.thrift.protocol.TField VAL_FIELD_DESC = new org.apache.thrift.protocol.TField("val", org.apache.thrift.protocol.TType.STRUCT, (short)3);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TransactionStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TransactionTupleSchemeFactory();

    public int transId; // required
    public int key; // required
    public @org.apache.thrift.annotation.Nullable Doc val; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        TRANS_ID((short)1, "transId"),
        KEY((short)2, "key"),
        VAL((short)3, "val");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch(fieldId) {
                case 1: // TRANS_ID
                    return TRANS_ID;
                case 2: // KEY
                    return KEY;
                case 3: // VAL
                    return VAL;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __TRANSID_ISSET_ID = 0;
    private static final int __KEY_ISSET_ID = 1;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.TRANS_ID, new org.apache.thrift.meta_data.FieldMetaData("transId", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        tmpMap.put(_Fields.KEY, new org.apache.thrift.meta_data.FieldMetaData("key", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        tmpMap.put(_Fields.VAL, new org.apache.thrift.meta_data.FieldMetaData("val", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Doc.class)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Transaction.class, metaDataMap);
    }

    public Transaction() {
    }

    public Transaction(
            int transId,
            int key,
            Doc val)
    {
        this();
        this.transId = transId;
        setTransIdIsSet(true);
        this.key = key;
        setKeyIsSet(true);
        this.val = val;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public Transaction(Transaction other) {
        __isset_bitfield = other.__isset_bitfield;
        this.transId = other.transId;
        this.key = other.key;
        if (other.isSetVal()) {
            this.val = new Doc(other.val);
        }
    }

    @Override
    public Transaction deepCopy() {
        return new Transaction(this);
    }

    @Override
    public void clear() {
        setTransIdIsSet(false);
        this.transId = 0;
        setKeyIsSet(false);
        this.key = 0;
        this.val = null;
    }

    public int getTransId() {
        return this.transId;
    }

    public Transaction setTransId(int transId) {
        this.transId = transId;
        setTransIdIsSet(true);
        return this;
    }

    public void unsetTransId() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TRANSID_ISSET_ID);
    }

    /** Returns true if field transId is set (has been assigned a value) and false otherwise */
    public boolean isSetTransId() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TRANSID_ISSET_ID);
    }

    public void setTransIdIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TRANSID_ISSET_ID, value);
    }

    public int getKey() {
        return this.key;
    }

    public Transaction setKey(int key) {
        this.key = key;
        setKeyIsSet(true);
        return this;
    }

    public void unsetKey() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __KEY_ISSET_ID);
    }

    /** Returns true if field key is set (has been assigned a value) and false otherwise */
    public boolean isSetKey() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __KEY_ISSET_ID);
    }

    public void setKeyIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __KEY_ISSET_ID, value);
    }

    @org.apache.thrift.annotation.Nullable
    public Doc getVal() {
        return this.val;
    }

    public Transaction setVal(@org.apache.thrift.annotation.Nullable Doc val) {
        this.val = val;
        return this;
    }

    public void unsetVal() {
        this.val = null;
    }

    /** Returns true if field val is set (has been assigned a value) and false otherwise */
    public boolean isSetVal() {
        return this.val != null;
    }

    public void setValIsSet(boolean value) {
        if (!value) {
            this.val = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case TRANS_ID:
                if (value == null) {
                    unsetTransId();
                } else {
                    setTransId((java.lang.Integer)value);
                }
                break;

            case KEY:
                if (value == null) {
                    unsetKey();
                } else {
                    setKey((java.lang.Integer)value);
                }
                break;

            case VAL:
                if (value == null) {
                    unsetVal();
                } else {
                    setVal((Doc)value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case TRANS_ID:
                return getTransId();

            case KEY:
                return getKey();

            case VAL:
                return getVal();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case TRANS_ID:
                return isSetTransId();
            case KEY:
                return isSetKey();
            case VAL:
                return isSetVal();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof Transaction)
            return this.equals((Transaction)that);
        return false;
    }

    public boolean equals(Transaction that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_transId = true;
        boolean that_present_transId = true;
        if (this_present_transId || that_present_transId) {
            if (!(this_present_transId && that_present_transId))
                return false;
            if (this.transId != that.transId)
                return false;
        }

        boolean this_present_key = true;
        boolean that_present_key = true;
        if (this_present_key || that_present_key) {
            if (!(this_present_key && that_present_key))
                return false;
            if (this.key != that.key)
                return false;
        }

        boolean this_present_val = true && this.isSetVal();
        boolean that_present_val = true && that.isSetVal();
        if (this_present_val || that_present_val) {
            if (!(this_present_val && that_present_val))
                return false;
            if (!this.val.equals(that.val))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + transId;

        hashCode = hashCode * 8191 + key;

        hashCode = hashCode * 8191 + ((isSetVal()) ? 131071 : 524287);
        if (isSetVal())
            hashCode = hashCode * 8191 + val.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(Transaction other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetTransId(), other.isSetTransId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTransId()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transId, other.transId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetKey(), other.isSetKey());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetKey()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key, other.key);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetVal(), other.isSetVal());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetVal()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.val, other.val);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("Transaction(");
        boolean first = true;

        sb.append("transId:");
        sb.append(this.transId);
        first = false;
        if (!first) sb.append(", ");
        sb.append("key:");
        sb.append(this.key);
        first = false;
        if (!first) sb.append(", ");
        sb.append("val:");
        if (this.val == null) {
            sb.append("null");
        } else {
            sb.append(this.val);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
        if (val != null) {
            val.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class TransactionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public TransactionStandardScheme getScheme() {
            return new TransactionStandardScheme();
        }
    }

    private static class TransactionStandardScheme extends org.apache.thrift.scheme.StandardScheme<Transaction> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, Transaction struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true)
            {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // TRANS_ID
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.transId = iprot.readI32();
                            struct.setTransIdIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // KEY
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.key = iprot.readI32();
                            struct.setKeyIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // VAL
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.val = new Doc();
                            struct.val.read(iprot);
                            struct.setValIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, Transaction struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            oprot.writeFieldBegin(TRANS_ID_FIELD_DESC);
            oprot.writeI32(struct.transId);
            oprot.writeFieldEnd();
            oprot.writeFieldBegin(KEY_FIELD_DESC);
            oprot.writeI32(struct.key);
            oprot.writeFieldEnd();
            if (struct.val != null) {
                oprot.writeFieldBegin(VAL_FIELD_DESC);
                struct.val.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class TransactionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public TransactionTupleScheme getScheme() {
            return new TransactionTupleScheme();
        }
    }

    private static class TransactionTupleScheme extends org.apache.thrift.scheme.TupleScheme<Transaction> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, Transaction struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetTransId()) {
                optionals.set(0);
            }
            if (struct.isSetKey()) {
                optionals.set(1);
            }
            if (struct.isSetVal()) {
                optionals.set(2);
            }
            oprot.writeBitSet(optionals, 3);
            if (struct.isSetTransId()) {
                oprot.writeI32(struct.transId);
            }
            if (struct.isSetKey()) {
                oprot.writeI32(struct.key);
            }
            if (struct.isSetVal()) {
                struct.val.write(oprot);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, Transaction struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(3);
            if (incoming.get(0)) {
                struct.transId = iprot.readI32();
                struct.setTransIdIsSet(true);
            }
            if (incoming.get(1)) {
                struct.key = iprot.readI32();
                struct.setKeyIsSet(true);
            }
            if (incoming.get(2)) {
                struct.val = new Doc();
                struct.val.read(iprot);
                struct.setValIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

